language: ruby
rvm:
  - ruby-2.5.0
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
services:
- mysql
env:
  global:
    - "RAILS_ENV=test"
    - secure: "u4FqklO9FOLvlKMQNmTmyyiYGNl1+hcdIZe7ScBdwgcRVR/xOxJMOSvqVkx07cm4aI6Vi3JuUpU+j6gWFU55+UHih8I6VFrrCu6DhRz+nimjK84quNK9c9EPaxk2ROlOm0lO0sNfxCliDsl58djLppWW7nmCX+If8JHZOJ49OvzFRK5IorMNZGXYbKZZSAYMMt8TPEDnfv9pgqWc7iRS5SOy+Dqy9CBiFuHLdY+ccrJ7N4pjBtUpT8QPbZgwTZrh3HhsP67V2SAWeZDuDVORwIseatg6KhYNUgHHDHTzvDNmgWWGdNUxSbPsppasbUZjlM+iQ00dpOCTsxNPaBCiPqpDG0EqsLc35wdF7NlD0OLlDmnCVLPLYUiSH4iunlPoiaJz/LcAckORwi7bjorbBy6kAdsR8ER+RYXYg938/5OK/FrBOKMwPzYCjSTNOq1O+ZcXtU6VQuMV9fv3gyJ30Qp9SFovmlYX4dd6UUByGRYY5iMAAuPCyv5p/3a7/FI7wmXCttZzLr+DLU1oA4LznCC7Fag+aAE4Ktobaak2cTmg/6LEkTs+M2stWA4rdX5Ei1iSBrRN4FECBCjNuh2YfizdcCyowa2RXIB445sEc2B46QiNOvRV0wCPFvjiYH2joevYQO6MtSXLn+qYQZphPffdjb33HBTAUGTMCwZq/mw="
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS todo_test'
before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate

  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    - nicolasganz37+travis@gmail.com
