test:
  secret_key_base: cd31bbd2dd4ecaf7d1ede8b60b6a66aa63f40f18db9e56047a78293d64990fc1acc03ad9878ddea687b3f882839483b867ea9bbeadd041498f9cab768daa9585
  database:
    host: localhost
    name: todo_test
    username: todo_test
    password: Rm5csQHH3z2dhiyJTUeqYNiuX6t5HbuKPmM
  omniauth:
    keltec:
      app_id: none
      app_secret: none
